// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: munition.proto

package munition

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MunitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamId  int32 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	AtCount int32 `protobuf:"varint,2,opt,name=at_count,json=atCount,proto3" json:"at_count,omitempty"`
	MpCount int32 `protobuf:"varint,3,opt,name=mp_count,json=mpCount,proto3" json:"mp_count,omitempty"`
}

func (x *MunitionRequest) Reset() {
	*x = MunitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_munition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MunitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MunitionRequest) ProtoMessage() {}

func (x *MunitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_munition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MunitionRequest.ProtoReflect.Descriptor instead.
func (*MunitionRequest) Descriptor() ([]byte, []int) {
	return file_munition_proto_rawDescGZIP(), []int{0}
}

func (x *MunitionRequest) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *MunitionRequest) GetAtCount() int32 {
	if x != nil {
		return x.AtCount
	}
	return 0
}

func (x *MunitionRequest) GetMpCount() int32 {
	if x != nil {
		return x.MpCount
	}
	return 0
}

type MunitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Granted bool   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MunitionResponse) Reset() {
	*x = MunitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_munition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MunitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MunitionResponse) ProtoMessage() {}

func (x *MunitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_munition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MunitionResponse.ProtoReflect.Descriptor instead.
func (*MunitionResponse) Descriptor() ([]byte, []int) {
	return file_munition_proto_rawDescGZIP(), []int{1}
}

func (x *MunitionResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *MunitionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_munition_proto protoreflect.FileDescriptor

var file_munition_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x60, 0x0a, 0x0f, 0x4d, 0x75,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x74, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x74, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x46, 0x0a, 0x10,
	0x4d, 0x75, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0x4d, 0x0a, 0x05, 0x45, 0x61, 0x72, 0x74, 0x68, 0x12, 0x44, 0x0a,
	0x0b, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x65, 0x4d, 0x12, 0x19, 0x2e, 0x6d,
	0x75, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x75, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x4d, 0x75, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_munition_proto_rawDescOnce sync.Once
	file_munition_proto_rawDescData = file_munition_proto_rawDesc
)

func file_munition_proto_rawDescGZIP() []byte {
	file_munition_proto_rawDescOnce.Do(func() {
		file_munition_proto_rawDescData = protoimpl.X.CompressGZIP(file_munition_proto_rawDescData)
	})
	return file_munition_proto_rawDescData
}

var file_munition_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_munition_proto_goTypes = []interface{}{
	(*MunitionRequest)(nil),  // 0: munition.MunitionRequest
	(*MunitionResponse)(nil), // 1: munition.MunitionResponse
}
var file_munition_proto_depIdxs = []int32{
	0, // 0: munition.Earth.SolicitudeM:input_type -> munition.MunitionRequest
	1, // 1: munition.Earth.SolicitudeM:output_type -> munition.MunitionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_munition_proto_init() }
func file_munition_proto_init() {
	if File_munition_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_munition_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MunitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_munition_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MunitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_munition_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_munition_proto_goTypes,
		DependencyIndexes: file_munition_proto_depIdxs,
		MessageInfos:      file_munition_proto_msgTypes,
	}.Build()
	File_munition_proto = out.File
	file_munition_proto_rawDesc = nil
	file_munition_proto_goTypes = nil
	file_munition_proto_depIdxs = nil
}
